steps:
  - id: kanikoBuild
    name: "us-central1-docker.pkg.dev/$PROJECT_ID/docker/kaniko:latest"
    entrypoint: "bash"
    args:
      [
        "-c",
        '/kaniko/executor --destination=us-central1-docker.pkg.dev/$PROJECT_ID/docker/vendor-push-notification-worker-image:$TAG_NAME --destination=us-central1-docker.pkg.dev/$PROJECT_ID/docker/vendor-push-notification-worker-image:latest --cache=true --cache-ttl=365h --build-arg GITHUBPRIVATEKEY="$(echo $$GITHUBPRIVATEKEY)"',
      ]
    secretEnv: ["GITHUBPRIVATEKEY"]

  - id: k8sApply
    name: "gcr.io/cloud-builders/kubectl"
    args: ["apply", "-f", "k8s/"]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-b"
      - "CLOUDSDK_CONTAINER_CLUSTER=ikomida-prod-cluster"
    waitFor:
      - kanikoBuild

  - id: k8sSetImage
    name: "gcr.io/cloud-builders/kubectl"
    args:
      [
        "-n",
        "ikomida-worker",
        "set",
        "image",
        "deployment",
        "vendor-push-notification-worker",
        "vendor-push-notification-worker=us-central1-docker.pkg.dev/ikomida-dev/docker/vendor-push-notification-worker-image:$TAG_NAME",
      ]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-b"
      - "CLOUDSDK_CONTAINER_CLUSTER=ikomida-prod-cluster"
    waitFor:
      - k8sApply

availableSecrets:
  secretManager:
    - versionName: projects/981415290588/secrets/github-privatekey/versions/1
      env: "GITHUBPRIVATEKEY"
