Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"
$PSDefaultParameterValues['*:ErrorAction']='Stop'
function ThrowOnNativeFailure {
    if (-not $?)
    {
        throw 'Native Failure'
    }
}
$projectid="ikomida-dev"
if($args.count -gt 0){
    $projectid=$args[0]
}
$nocache=""
if($args.count -gt 1){
    $nocache=$args[1]
}
$env:GOOGLE_SERVICE_ACCOUNT="ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiaWtvbWlkYS1wcm9kIiwKICAicHJpdmF0ZV9rZXlfaWQiOiAiZDkwMTYxMDE1ZmFlY2FlMzhmZmZiOTY1NThhMzEzY2JiMmM4ZmQzOCIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuTUlJRXZRSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS2N3Z2dTakFnRUFBb0lCQVFDL29KUnMyblZNMU1xUVxucW8zbWZHbGN0ekdJZWk2anRCSURDRDEvaG91UFl2TGs5aVdaWnBQc1VKajNhc3JzYjd5b2ZVc2dRZEVmdWhRNlxuaWJhbS9CNmpzb3FrcDNlU2lVNG8zWGdreUtMNFJwbG5McUYvZnB4QzlJQVNmZCtCa2p3RDhvQlNhcU40T2NBRFxudW1GWHo4WjFEa3Vzb29vY042bUN1QldMQ3AwcDA3NmFVREdwOWlTRjFxcEpVcDRCR3lKWE5EbEl6U2g2QnVMdFxuWTVkNjlWdnJOdDVUN1UweXpPZ0taS1RmM0RwUkYvM3FXY2s3VjFRQ0IwajlJZkNxeHYvT21ldDZXWUwwRjBFeVxuZ3h5TW13MklwcGRVRjU4UkYwS3h4a0dTOTNEd3prTllMOERuZFdUYkticlp2cGljRGxPME4yc3NhWWVzOGhWblxuTjNZaHhDZ3BBZ01CQUFFQ2dnRUFPcjRGQWVGdDkrRjdQeUdwWWpCZE5Cak1UR1A0RENMVktxekovVi9IUkdzMlxudmsxZWRVbm1xcGlDYThZRzhyZkdBM2gxSVN4TDZRZm56NUlMdGVDdm04ck5pVy8wemF6ZGt0VmhVUlZZTC9la1xuYXViMmh0alBHZzlOZTEydXVFK1ZxamdhY2lsU2R6WnMwRGZBUTJUa0Yxb01oSjFHN1NON0NTRlpLVWhWcVU1QlxuRURxRXJvVW5yVTVaUFdsVjUyRlRseUdnS29NN2hWNHRobUQvenBqa0VTN3ZIbjMvWnlmblF0bkdZZ1E2ckd5aFxuNFNYd1Zvd0RBWlpuRzVWTzdZSllmazhpQ082QTdUbnA0d2o3OXJET1psSXZzRnNSNzhHN1NFOEhFblMwbzlHS1xudkhudkxUazlWS1FZNFZSNWdxcnNsODNHZ1luM0xDS1JXb1IvVUc5d0NRS0JnUUQzT1ZhbFdFMlBwQ09EdmJGNFxuWk9pa2xSMzhxRythcWdlKzVocHlmZGg4VVMvZ3pNYmNFRGhXRjIwSHlXWXh6SlNMVnFCWmdUL1QzRWtXdlBCelxuYnlaalJDQmJBWG42MzUvN3RRd0pieWhIeXBYLzdFVFVsNlRqVVRoTGxGaEl3M0xMVkFIejEzYzM3Qit3amg0OVxueTROd1FFbEJjMjd3cXFRbG9wNTJEWEk0L3dLQmdRREdiZ0RNd2hPS2VrNDR4VDZVRkhKZTNUYVdMaGpSMHp5elxucnAyWnQzUFlxekVRRUNVZU4zWXZzWThJR20zUmRnVnJOdTlFbVgzYTlPdXR3TFhnLzEwbTNlc2w1RWx6U1pFTVxuWkJJVzBJWWFGWi80d0tmUnBwWGl4MmpKSmFSK3NYSUVLT3VSc1VJMjJWdkhHUkpkaHVqd1VFd1NpaWdGYVB6elxuWmdZSFZLKzIxd0tCZ1FETFk5dlo2ZnpkYU45aStnUHdsYXdrQXg0SmlCVlJQQU5sVlc5NnMvZ1B4c2RKL1k2NFxuNjRzOW9NWXRlczdkdDM2WjUrbkIyU2pHeHR0R25xaC9mM2tvZjVyUzVETVRaemo2WHVlSk4yNy9LVGNndHFPbFxuOXlCTGQ3MkZ5SVNkVUZhMzJ1UkVWUWFhOW1MWDRRUVdPTUZvN3lxVmN6OVpOam9YVUdObm9nWlB4d0tCZ0VhSVxuRFZLNjNYVkllZ3RsMlJPTG5RZXBPK0R2NjdTUmtDOFNMMFRYVjU4NVlvd2lJUDkzbVZQa21rRzRHemJyNjRzclxua0tyaW9FQzI5QnJqdUFLTTRwQ1JLeWRoMk5YWTNXejVHUkR3OStuSHJBQWdnc1pibjBWbnVoQmRoL1hjbnZscFxuamlwUVJvZjJoTS9sVW9qYURteDFMa1VjeEpML3VZSE96dS9HSTFzckFvR0FYcTltdUloL3NXNHZkMFJpcnozeFxuZFBsTDlMYWpwZXk4N1BDOTVqMTNGeWVsQUtCUy9kVVVUMHZpMjJkRjJZNXRxQzVaZllpM0hVLzFlRW11Z29iWVxuWXE2M0IzYy9UZkVGdjMrSXpWakowRldwZUlZTjM0U2xhN2xYY0dzZE1FVExIbUttRkpZdjFjZmY0Ryt1Q2ROSFxudXdkMU1Ha0tIOHJHbFhLTnhGbTR2Wm89XG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLAogICJjbGllbnRfZW1haWwiOiAiYXJ0aWZhY3QtcmVnaXN0cnlAaWtvbWlkYS1wcm9kLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAiY2xpZW50X2lkIjogIjExODM4OTE5NDcwNjM4ODIwMjk1NiIsCiAgImF1dGhfdXJpIjogImh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi9hdXRoIiwKICAidG9rZW5fdXJpIjogImh0dHBzOi8vb2F1dGgyLmdvb2dsZWFwaXMuY29tL3Rva2VuIiwKICAiYXV0aF9wcm92aWRlcl94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsCiAgImNsaWVudF94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkvYXJ0aWZhY3QtcmVnaXN0cnklNDBpa29taWRhLXByb2QuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iCn0="
yarn glogin
ThrowOnNativeFailure
yarn add @ikomida/shared-backend@latest
ThrowOnNativeFailure
docker build -t us-central1-docker.pkg.dev/$projectid/docker/vendor-push-notification-worker-image:latest . --build-arg GOOGLE_SERVICE_ACCOUNT="$env:GOOGLE_SERVICE_ACCOUNT"  --build-arg NODEENV=devlopment --build-arg PROJECT_ID=$projectid $nocache
ThrowOnNativeFailure
docker push us-central1-docker.pkg.dev/$projectid/docker/vendor-push-notification-worker-image:latest
ThrowOnNativeFailure
kubectl -n ikomida-worker delete deploy vendor-push-notification-worker

Get-ChildItem ".\k8s\" -Filter *.yaml | 
Foreach-Object {
    $content = Get-Content $_.FullName
    $content.replace('$PROJECT_ID', $projectid) | kubectl apply -f -
}