apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: $NAME
  name: $NAME-$TYPE
  namespace: ikomida-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $NAME
  template:
    metadata:
      labels:
        app: $NAME
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
        runAsNonRoot: true
      containers:
        - image: $GCLOUD_LOCATION-docker.pkg.dev/$PROJECT_ID/docker/$NAME-$TYPE-image:$PACKAGE_VERSION
          name: $NAME-$TYPE
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            privileged: false
            readOnlyRootFilesystem: true
          resources:
            requests:
              cpu: "18m"
              memory: "72Mi"
            limits:
              cpu: "150m"
          env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: NODE_ENV
                  optional: false
            - name: IKOMIDA_PRIVATEKEY
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: IKOMIDA_PRIVATEKEY
                  optional: false
            - name: IKOMIDA_PUBLICKEY
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: IKOMIDA_PUBLICKEY
                  optional: false
            - name: GOOGLEADMIN
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: googleAdmin
                  optional: false
            - name: DBUSER
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: DBUSER
            - name: DBPASS
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: DBPASS
            - name: DBNAME
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: DBNAME
            - name: DBHOST
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: DBHOST
            - name: DBPORT
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: DBPORT
            - name: MQUSER
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: MQUSER
            - name: MQPASS
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: MQPASS
            - name: MQVHOST
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: MQVHOST
            - name: PROJID
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: PROJID
            - name: APPLE_APNS
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: APPLE_APNS
            - name: APPLE_APNS_KEY
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: APPLE_APNS_KEY
