apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vendor-push-notification
  name: vendor-push-notification-worker
  namespace: ikomida-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vendor-push-notification
  template:
    metadata:
      labels:
        app: vendor-push-notification
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
        runAsNonRoot: true
      containers:
        - image: us-central1-docker.pkg.dev/ikomida-prod/docker/vendor-push-notification-worker-image:latest
          name: vendor-push-notification-worker
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: ENV
              value: "PROD"
            - name: IKOMIDA_PRIVATEKEY
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: ikomidaPrivateKey
                  optional: false
            - name: IKOMIDA_PUBLICKEY
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: ikomidaPublickey
                  optional: false
            - name: GOOGLEADMIN
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: googleAdmin
                  optional: false
            - name: DBUSER
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: DBUSER
            - name: DBPASS
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: DBPASS
            - name: DBNAME
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: DBNAME
            - name: DBHOST
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: DBHOST
            - name: DBPORT
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: DBPORT
            - name: MQUSER
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: MQUSER
            - name: MQPASS
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: MQPASS
            - name: MQVHOST
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: MQVHOST
            - name: PROJID
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: PROJID
